services:
  - type: web
    name: distributed-simulation-engine-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
